version: '3.3'
services:
  ldes-server:
    environment:
      - MONGO_URL=
      - MONGO_DATABASE=ldes
      - MONGO_USERNAME=
      - MONGO_PASSWORD=
      - LDES_ENDPOINT=http://localhost:8080
    ports:
      - '8080:8080'
    image: ldes-server
    networks:
      - isolation-network
  ldes-client:
    ports:
      - '8443:8443'
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    image: ldes-client
    networks:
      - isolation-network
networks:
  isolation-network:
    driver: bridge