# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'general'
    scrape_interval: 500ms
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
        - 'host.docker.internal:8080'
        - 'host.docker.internal:8081'