{
 "title": "VSDS Demo board",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Members Ingested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ldes_server_ingested_members_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Fragments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ldes_server_create_fragments_count_total",
     "legendFormat": "__auto"
    },
    {
     "expression": "$Fragments - $Fragments_Deleted",
     "type": "math"
    },
    {
     "expr": "ldes_server_deleted_members_count OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDIO I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "ldio_data_in_total", "legendFormat": "__auto" },
    { "expr": "ldio_data_out_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Pyroscope", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "LDES Server",
   "type": "flamegraph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "labelSelector": "{service_name=\"ldes-server\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  }
 ]
}