# config file version
apiVersion: 1

# list of datasources to insert/update
datasources:
- name: Prometheus
  access: proxy
  type: prometheus
  url: http://host.docker.internal:9090
  isDefault: true
- name: Jaeger
  access: proxy
  type: jaeger
  url: http://host.docker.internal:16686
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://host.docker.internal:3100
  basicAuth: false
  version: 1
  editable: false