version: '3.3'
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.58.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./resources/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "5567:55679" # zpages extension
    networks:
      - otel

  jaeger:
    image: jaegertracing/all-in-one:1.37
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "4319:4317"
      - "4320:4318"
      - "14250:14250"
    depends_on:
      - otel-collector
    networks:
      - otel
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./resources/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    networks:
      - otel
    restart: always
  grafana:
    image: grafana/grafana
    user: "472"
    ports:
      - "3000:3000"
    volumes:
      - ./resources/grafana/:/etc/grafana/
    networks:
      - otel
    restart: always

networks:
  otel:
    driver: bridge
